name: Typechecks and integration testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6

    - name: Install deps
      run: pnpm install

    - name: Test discord bot
      working-directory: ./packages/discord-bot
      run: pnpm test

    - name: Typecheck webapp
      working-directory: ./packages/web
      run: pnpm test
